# Generated by Django 4.2.5 on 2023-10-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[(3, 'Daily'), (2, 'Weekly'), (1, 'Monthly'), (0, 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=9)),
                ('group', models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable'), ('Discretionary', 'Discretionary'), ('Income', 'Income'), ('Savings', 'Savings')], max_length=50)),
                ('rule', models.ForeignKey(blank=True, help_text='Leave blank for a one time only event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rule')),
            ],
        ),
    ]
